# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/helpdesk
spring.datasource.username=postgres
spring.datasource.password=thedriver829

# Automatically create/update tables from entities
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console
spring.jpa.show-sql=true

# Format SQL nicely
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#JWT config
jwt.secret=O1Bgz5DmsHs0Idn71itPBCSp22t4rZcMd8XJMosoTxngLHLCx7Ca0TXgefI7Lm6YqhzX6VJfzkRr3vVwmuliUg==
jwt.expiration=86400000